In [1]:
import pandas as pd
import tensorflow_hub as hub
import h5py

In [2]:
fname = "/project/def-psavard/ladamek/ArxivFiles/arxiv-metadata-oai-snapshot.hdf"
data= pd.read_hdf(fname,key="abstract_data")
data["abstracts"].astype('string')
def clean_data(data):
    data["abstracts"] = data["abstracts"].str.replace("\n", " ")
    data["abstracts"] = data["abstracts"].str.replace(r"\$[^\$]*\$\-", " ", regex=True)
    data["abstracts"] = data["abstracts"].str.replace(r"\$[^\$]*\$", " ", regex=True)
    #data["abstracts"] = data["abstracts"].str.replace(r"\$[^\$]*\$\", "", regex=True)
    #data["abstracts"] = data["abstracts"].str.replace(r"", "", regex=True)
    data["abstracts"] = data["abstracts"].str.replace(r"  ", " ", regex=True)
    return data
data = clean_data(data)
data

abstracts  Physics  \
0         We describe a new algorithm, the pebble game ...        0   
1         The evolution of Earth-Moon system is describ...        1   
2         We show that a determinant of Stirling cycle ...        0   
3         In this paper we show how to compute the  nor...        0   
4         We study the two-particle wave function of pa...        1   
...                                                    ...      ...   
1565955   We report on measurements of the angular depe...        1   
1565956   The non-linear microwave surface impedance of...        1   
1565957   The vortex contribution to the dc field (H) d...        1   
1565958   We show that the density of states in an anis...        1   
1565959   The Ginzburg Landau theory for d_{x^2-y^2}-wa...        1   

         Mathematics  Computer Science  Quantitative Biology  \
0                  1                 1                     0   
1                  0                 0                     0   
2                  1                 0                     0   
3                  1                 0                     0   
4                  0                 0                     0   
...              ...               ...                   ...   
1565955            0                 0                     0   
1565956            0                 0                     0   
1565957            0                 0                     0   
1565958            0                 0                     0   
1565959            0                 0                     0   

         Quantitative Finance  Statistics  \
0                           0           0   
1                           0           0   
2                           0           0   
3                           0           0   
4                           0           0   
...                       ...         ...   
1565955                     0           0   
1565956                     0           0   
1565957                     0           0   
1565958                     0           0   
1565959                     0           0   

         Electrical Engineering and Systems Science  Economics  
0                                                 0          0  
1                                                 0          0  
2                                                 0          0  
3                                                 0          0  
4                                                 0          0  
...                                             ...        ...  
1565955                                           0          0  
1565956                                           0          0  
1565957                                           0          0  
1565958                                           0          0  
1565959                                           0          0  

[1565960 rows x 9 columns]

In [3]:
data["abstracts"].values[-1]

" The Ginzburg Landau theory for d_{x^2-y^2}-wave superconductors is constructed, by starting from the Gor'kov equation with including correction terms up to the next order of ln(T_c/T). Some of the non-local correction terms are found to break the cylindrical symmetry and lead to the fourfold symmetric core structure, reflecting the internal degree of freedom in the pair potential. Using this extended Ginzburg Landau theory, we investigate the fourfold symmetric structure of the pair potential, current and magnetic field around an isolated single vortex, and clarify concretely how the vortex core structure deviates from the cylindrical symmetry in the d_{x^2-y^2}-wave superconductors. "

In [4]:
embed = hub.load("../EmbeddingModels/universal-sentence-encoder-large_4")

2022-03-25 16:42:35.783809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-03-25 16:42:37.583057: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-03-25 16:42:37.583238: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (gra827): /proc/driver/nvidia/version does not exist
2022-03-25 16:42:37.585827: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-03-25 16:42:37.622217: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2095074999 Hz
2022-03-25 16:42:37.622500: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2b1bf4000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-03-25 16:42:

In [5]:
subdata = data[0:100]
subdata = {c:subdata[c].values for c in subdata}
embeddings = embed(subdata["abstracts"]) # process about 1000 at a time
embeddings

{'outputs': <tf.Tensor: shape=(100, 512), dtype=float32, numpy=
 array([[-0.04575021,  0.04444352, -0.08450314, ...,  0.08418953,
          0.00879304, -0.01011373],
        [ 0.01438187,  0.03046808,  0.06087292, ...,  0.07106357,
          0.05783188, -0.01010555],
        [ 0.0640423 ,  0.00550433, -0.02312865, ..., -0.02769209,
         -0.04957713, -0.05708123],
        ...,
        [ 0.08821163,  0.0113154 , -0.08078555, ..., -0.00645896,
          0.00966444,  0.0270819 ],
        [ 0.06118148,  0.01833446, -0.01217962, ...,  0.07329561,
          0.05255608, -0.01519746],
        [-0.01301717,  0.05586116, -0.06447063, ...,  0.03969995,
          0.01569352, -0.05422472]], dtype=float32)>}

In [6]:
subdata["full_embeddings"] = embeddings["outputs"].numpy()

In [7]:
subdata["full_embeddings"]

array([[-0.04575021,  0.04444352, -0.08450314, ...,  0.08418953,
         0.00879304, -0.01011373],
       [ 0.01438187,  0.03046808,  0.06087292, ...,  0.07106357,
         0.05783188, -0.01010555],
       [ 0.0640423 ,  0.00550433, -0.02312865, ..., -0.02769209,
        -0.04957713, -0.05708123],
       ...,
       [ 0.08821163,  0.0113154 , -0.08078555, ..., -0.00645896,
         0.00966444,  0.0270819 ],
       [ 0.06118148,  0.01833446, -0.01217962, ...,  0.07329561,
         0.05255608, -0.01519746],
       [-0.01301717,  0.05586116, -0.06447063, ...,  0.03969995,
         0.01569352, -0.05422472]], dtype=float32)

In [8]:
subdata["Physics"]

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [9]:
subdata["Computer Science"]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [10]:
physics_entries = subdata["Physics"] == 1
computer_science_entries = subdata["Computer Science"] == 1

In [11]:
def apply_selection(data,sel):
    return {key:data[key][sel] for key in data}
physics_data = apply_selection(subdata, physics_entries)
computer_data = apply_selection(subdata, computer_science_entries)

def calc_cosine(v1, v2):
    dot = np.sum(v1* v2, axis=1)
    mag1, mag2 = np.sum(v1**2, axis=1), np.sum(v2**2, axis=1)
    return dot/(mag1*mag2)

In [12]:
import numpy as np
np.average(calc_cosine(physics_data["full_embeddings"][0:10], physics_data["full_embeddings"][1:11]))

0.44354877

In [13]:
import numpy as np
np.average(calc_cosine(computer_data["full_embeddings"][0:8], physics_data["full_embeddings"][0:8]))

0.28206646